package com.ute.myapp.constant;

public class Constant {
    public static final int COLUMNS_GENRE = 2;
    public static final String USERS = "users";
    public static final String USERNAME = "userName";
    public static final String USER = "user";
    public static final String PNG = "png";
    public static final String JPG = "jpg";
    public static final String JPEG = "jpeg";
    public static final String PREF_NAME = "MyPreferences";
    public static final String KEY_USERNAME = "userName";
    public static final String KEY_PASSWORD = "password";
    public static final String KEY_LOGGED_IN = "loggedIn";
    public static final String KEY_USER = "user";
    public static String DEFAULT_AVATAR_URL = "https://firebasestorage.googleapis.com/v0/b/myapp-43e9b.appspot.com/o/users%2Fdefault_avatar.png?alt=media&token=331437dc-8abb-41e4-bc3b-06fb2f189968";
    public static String DEFAULT_ROLE_NAME = "user";
    public static boolean DEFAULT_STATUS = true;
    public static int COST = 4;
    public static String ADMIN = "admin";
    public static String CONTENT_MANAGER = "content_manager";
    public static String AUTHOR = "author";
    public static int MARGIN_DIALOG = 16;
    public static final String GENRES = "genres";
    public static final String GENRE_NAME = "genreName";
    public static final String LIST_GENRE = "listGenre";
    public static final String GENRE_STATUS = "status";
    public static final String USER_STATUS = "status";
    public static final String LIST_USER = "listUser";
    public static final String REGISTER = "register";
    public static final String CREATE_ACTIVE_ACCOUNT = "createActiveAccount";
    public static final String CONVERT_USER = "Người dùng";
    public static final String CONVERT_AUTHOR = "Tác giả";
    public static final String CONVERT_CONTENT_MANAGER = "Quản lý nội dung";
    public static final String DEFAULT_LOCKED_DATE = "2022-05-06T14:11:32.887";
    public static final String LOCKED_TIME_PREFIX = "Tài khoản sẽ được mở khóa sau ";
    public static final String STORIES = "stories";
    public static final String STORY_NAME = "storyName";
    public static final String AUTHOR_NAME = "authorName";
    public static final String WITH_CHAPTER = "withChapter";
    public static final String CONTENT = "content";
    public static final String STORY_STATUS = "status";
    public static final String STORY_ID = "storyId";
    public static final String LIST_STORY = "listStory";
    public static final String STORY_WITH_CHAPTER = "Có chương";
    public static final String STORY_WITHOUT_CHAPTER = "Không có chương";
    public static final String ACTIVE = "Hoạt động";
    public static final String INACTIVE = "Bị khóa";
    public static final String MAP_STORY = "mapStory";
    public static final String CHAPTER = "chapter";
    public static final String PASSWORD = "password";
    public static final String MINE_IMAGE = "image/*";
    public static final String IMAGE_URL = "imageUrl";
    public static final String USER_NAME = "userName";
    public static final String FIRST_NAME = "firstName";
    public static final String LAST_NAME = "lastName";
    public static final String PHONE = "phone";
    public static final String DATE_OF_BIRTH = "dateOfBirth";
    public static final String EMAIL = "email";
    public static final String ROLE_NAME = "roleName";
    public static final String LOCKED_TIME = "lockedTime";
    public static final String APP_NAME = "Sách ma pháp";
    public static final String CLAIM = "claim";
    public static final String MINE_TEXT_HTML = "text/html; charset=UTF-8";
    public static final String USER_ID = "userId";
    public static final String APPROVE = "approve";
    public static final String IMAGE_PATH = "imagePath";
}
